[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "x_logger"

version = "0.2.7"

description = "logger"
authors = [
  { name="Kengo NAKADA", email="kengo.nakada@email.com" }
]
readme = "README.md"
requires-python = ">=3.8"

dependencies = [
"colorlog",
"coloredlogs",
#
"sphinx",
"myst-parser",
"sphinx-autobuild",
"sphinx-rtd-theme",
"sphinxcontrib-napoleon",
"linkify-it-py"
]

[tool.pytest.ini_options]
pythonpath = ["src"]

# ここでpytestのiniと同じようにオプションが書ける
# 例えばテストマーク、フィルタ、カバレッジなども追記可能

[tool.black]
line-length = 88

[tool.isort]
profile = "black"